// eslint-disable-next-line import/prefer-default-export
export const ERROR_CODES = {
  AUTHENTICATION_ERROR_SESSION: "AUTHENTICATION_ERROR@TOKEN_EXPIRED",
  AUTHENTICATION_ERROR_RESIGN_IN: "AUTHENTICATION_ERROR@NEED_REAUTHENTICATE",
  LACK_OF_DATA: "LACK_OF_DATA",
  BAD_USER_INPUT: "BAD_USER_INPUT",
};
